package ontology;

import java.util.List;

import ontology.Data.Individuals;
import ontology.Data.Verbs;

public class Stories {
        public static final List<List<ParsedSentence>> stories = List.of(
                        List.of(
                                        new ParsedSentence(Verbs.celebrate, List.of(Individuals.birthday,
                                                        Individuals.home), false, "A birthday was celebrated at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.alice,
                                                        Individuals.birthday), false,
                                                        "Alice attended the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.alice, Individuals.home),
                                                        false,
                                                        "Alice was at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.bob,
                                                        Individuals.birthday), false,
                                                        "Bob attended the birthday celebration."),
                                        new ParsedSentence(Verbs.bring, List.of(Individuals.charlie,
                                                        Individuals.cake, Individuals.home), false,
                                                        "Charlie brought a cake to the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.john, Individuals.home),
                                                        false,
                                                        "John was at home."),
                                        new ParsedSentence(Verbs.murder,
                                                        List.of(Individuals.unknownHuman, Individuals.alice,
                                                                        Individuals.home),
                                                        false,
                                                        "Someone murdered Alice at home."),
                                        new ParsedSentence(Verbs.investigate, List.of(Individuals.david,
                                                        Individuals.john,
                                                        Individuals.alice, Individuals.home), false,
                                                        "David investigated John for a murder of Alice at home."),
                                        new ParsedSentence(Verbs.murder, List.of(Individuals.john, Individuals.alice),
                                                        false, "John murdered Alice.")),
                        List.of(
                                        new ParsedSentence(Verbs.celebrate, List.of(Individuals.birthday,
                                                        Individuals.home), false, "A birthday was celebrated at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.alice,
                                                        Individuals.birthday), false,
                                                        "Alice attended the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.alice, Individuals.home),
                                                        false,
                                                        "Alice was at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.bob,
                                                        Individuals.birthday), false,
                                                        "Bob attended the birthday celebration."),
                                        new ParsedSentence(Verbs.bring, List.of(Individuals.charlie,
                                                        Individuals.cake, Individuals.home), false,
                                                        "Charlie brought a cake to the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.john, Individuals.home),
                                                        false,
                                                        "John was at home."),
                                        new ParsedSentence(Verbs.murder,
                                                        List.of(Individuals.unknownHuman, Individuals.alice,
                                                                        Individuals.home),
                                                        false,
                                                        "Someone murdered Alice at home."),
                                        new ParsedSentence(Verbs.investigate, List.of(Individuals.david,
                                                        Individuals.john,
                                                        Individuals.alice, Individuals.home), false,
                                                        "David investigated John for a murder of Alice at home."),
                                        new ParsedSentence(Verbs.murder, List.of(Individuals.charlie,
                                                        Individuals.alice), true,
                                                        "Charlie did not murder Alice."),
                                        new ParsedSentence(Verbs.murder, List.of(Individuals.john, Individuals.alice),
                                                        false, "John murdered Alice.")),
                        List.of(
                                        new ParsedSentence(Verbs.celebrate, List.of(Individuals.birthday,
                                                        Individuals.home), false, "A birthday was celebrated at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.alice,
                                                        Individuals.birthday), false,
                                                        "Alice attended the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.alice, Individuals.home),
                                                        false,
                                                        "Alice was at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.bob,
                                                        Individuals.birthday), false,
                                                        "Bob attended the birthday celebration."),
                                        new ParsedSentence(Verbs.bring, List.of(Individuals.charlie,
                                                        Individuals.cake, Individuals.home), false,
                                                        "Charlie brought a cake to the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.john, Individuals.home),
                                                        false,
                                                        "John was at home."),
                                        new ParsedSentence(Verbs.murder,
                                                        List.of(Individuals.unknownHuman, Individuals.alice,
                                                                        Individuals.home),
                                                        false,
                                                        "Someone murdered Alice at home."),
                                        new ParsedSentence(Verbs.investigate, List.of(Individuals.david,
                                                        Individuals.john,
                                                        Individuals.alice, Individuals.home), false,
                                                        "David investigated John for a murder of Alice at home."),
                                        new ParsedSentence(Verbs.investigate, List.of(Individuals.david,
                                                        Individuals.charlie,
                                                        Individuals.alice, Individuals.home), false,
                                                        "David investigated Charlie for a murder of Alice at home."),
                                        new ParsedSentence(Verbs.murder, List.of(Individuals.charlie,
                                                        Individuals.alice), true,
                                                        "Charlie did not murder Alice."),
                                        new ParsedSentence(Verbs.murder, List.of(Individuals.john, Individuals.alice),
                                                        false, "John murdered Alice.")),

                        List.of(
                                        new ParsedSentence(Verbs.celebrate, List.of(Individuals.birthday,
                                                        Individuals.home), false, "A birthday was celebrated at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.alice,
                                                        Individuals.birthday), false,
                                                        "Alice attended the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.alice, Individuals.home),
                                                        false,
                                                        "Alice was at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.bob,
                                                        Individuals.birthday), false,
                                                        "Bob attended the birthday celebration."),
                                        new ParsedSentence(Verbs.bring, List.of(Individuals.charlie,
                                                        Individuals.cake, Individuals.home), false,
                                                        "Charlie brought a cake to the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.john, Individuals.home),
                                                        false,
                                                        "John was at home."),
                                        new ParsedSentence(Verbs.murder,
                                                        List.of(Individuals.unknownHuman, Individuals.alice,
                                                                        Individuals.home),
                                                        false,
                                                        "Someone murdered Alice at home."),
                                        new ParsedSentence(Verbs.investigate, List.of(Individuals.david,
                                                        Individuals.john,
                                                        Individuals.unknownHuman, Individuals.unknownLocation), false,
                                                        "David investigated John for a murder of someone at some location."),
                                        new ParsedSentence(Verbs.murder, List.of(Individuals.john, Individuals.alice),
                                                        false, "John murdered Alice.")),
                        List.of(
                                        new ParsedSentence(Verbs.celebrate, List.of(Individuals.birthday,
                                                        Individuals.home), false, "A birthday was celebrated at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.alice,
                                                        Individuals.birthday), false,
                                                        "Alice attended the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.alice, Individuals.home),
                                                        false,
                                                        "Alice was at home."),
                                        new ParsedSentence(Verbs.attend, List.of(Individuals.bob,
                                                        Individuals.birthday), false,
                                                        "Bob attended the birthday celebration."),
                                        new ParsedSentence(Verbs.bring, List.of(Individuals.charlie,
                                                        Individuals.cake, Individuals.home), false,
                                                        "Charlie brought a cake to the birthday celebration."),
                                        new ParsedSentence(Verbs.beAt, List.of(Individuals.john, Individuals.home),
                                                        false,
                                                        "John was at home."),
                                        new ParsedSentence(Verbs.murder,
                                                        List.of(Individuals.unknownHuman, Individuals.alice,
                                                                        Individuals.home),
                                                        false,
                                                        "Someone murdered Alice at home."),
                                        new ParsedSentence(Verbs.investigate, List.of(Individuals.david,
                                                        Individuals.unknownHuman,
                                                        Individuals.unknownHuman, Individuals.unknownLocation), false,
                                                        "David investigated John for a murder of someone at some location."),
                                        new ParsedSentence(Verbs.murder, List.of(Individuals.charlie,
                                                        Individuals.alice), true,
                                                        "Charlie did not murder Alice."),
                                        new ParsedSentence(Verbs.murder, List.of(Individuals.john, Individuals.alice),
                                                        false, "John murdered Alice."))

        );
}
